name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    run: mvn verify sonar:sonar \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.organization=armanalemirad \
      -Dsonar.projectKey=ArmanAlemirad_Lab3
  
      mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      sonar:sonar -Pcoverage
